[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "survey-report-generator"
version = "0.0.1"
authors = [
    { name="Oliver Hahn", email="oliver.a.hahn@gmail.com" },
]
description = "A tool to generate survey reports from collected data"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/nsw-wildlife-drone-hub/report-generator"