[tool.poetry]
name = "python-web-io"
version = "0.1.13"
description = "Generate a webpage as a GUI for a Python script, and serve from anywhere."
authors = ["Zachary Smith <zachsmith.dev@gmail.com>"]
packages = [{include = "python_web_io"}]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cutwell/python-web-io"

[tool.poetry.dependencies]
python = "^3.10"
toml = "^0.10.2"
markdown = "^3.4.3"
fastapi = {extras = ["all"], version = "^0.101.0"}
jinja2 = "^3.1.2"
pydantic = "^2.1.1"
uvicorn = "^0.23.2"
watchdog = "^3.0.0"
python-multipart = "^0.0.6"
starsessions = "^2.1.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pre-commit = "^3.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"