[tool.poetry]
name = "nsj-flask-utils"
version = "0.1.1"
description = "Utils for Flask"
authors = ["Vinicius Teshima <viniciusteshima@nasajon.com.br>"]
license = "MIT License"
readme = "README.md"
packages = [{include = "nsj_flask_utils"}]

[tool.poetry.dependencies]
python = "3.11.4"
pydantic = "^2.1.1"
Flask = "^2.3.2"
SQLAlchemy = "^2.0.19"


[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
pyright = "^1.1.320"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
