[tool.poetry]
name = "powerjira"
version = "0.3.4"
description = "A succinct, minimal local jira control plane that can live in your text editor. Interface with tickets fast!"
authors = ["sleepyboy <anthonybenchyep@gmail.com>"]
license = "GNU GPL"
readme = "README.md"
repository = "https://github.com/anthonybench/powerjira"
keywords = ["jira", "poetry"]
packages = [
  { include = "powerjira.py" },
  { include = "toolchain/commands.py" },
  { include = "toolchain/utils.py" },
]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
jira = "^3.4.1"
typer = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
