[package]
name = "nova-python"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nova_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
reqwest = "0.11.18"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "time"] }
serde_json = "1.0.104" 