[project]
name = "graia-amnesia"
version = "0.8.0"
authors = [
    { name = "GreyElaina", email = "GreyElaina@outlook.com" },
]
requires-python = ">=3.8,<4.0"
dependencies = [
    "launart>=0.7.0,<1.0.0",
    "typing-extensions>=4.0.0",
]
readme = "README.md"
description = "a collection of shared components for graia"

[project.license]
text = "MIT"

[project.urls]

[project.optional-dependencies]

[tool.pdm.build]
includes = [
    "src/graia",
]

[tool.pdm.dev-dependencies]
dev = [
    "black<23.0.0,>=22.1.0",
]

[tool.black]
line_length = 120

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
