[tool.poetry]
name = "fast-openai"
version = "0.1.5"
description = ""
authors = ["Oscar Bahamonde <oscar.bahamonde@pucp.pe>"]
readme = "README.md"
packages = [{include = "fast_openai"}]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.68.1"
python-multipart = "^0.0.6"
aiohttp = "^3.8.5"
iso8601 = "^2.0.0"
openai = "^0.27.8"
tiktoken = "^0.4.0"
numpy = "^1.25.2"
jinja2 = "^3.1.2"
python-dotenv = "^1.0.0"
rich = "^13.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
