[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "msplotter"
version = "0.1.36"
authors = [
    {name = "Ivan MuÃ±oz-Gutierrez", email = "ivan.munoz.gutierrez@gmail.com"},
]
description = "Make a graphical representation of a blastn alignment"
readme = "README.md"
requires-python = ">=3.11"
keywords = [
    "blast", "alignment", "graphical representation", "DNA sequence",
    "easyfig"
]
license = {text = "BSD 3-Clause License"}
classifiers = [
    "Programming Language :: Python",
    "License :: OSI Approved :: BSD License",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "biopython==1.81",
    "customtkinter==5.1.3",
    "matplotlib==3.7.1"
]

[project.urls]
"Homepage" = "https://github.com/ivanmugu/MSPlotter"

[project.scripts]
msplotter = "msp.__main__:main"