[tool.poetry]
name = "dzdata"
version = "0.1.1"
description = "Object and dataset saved as a directory or zipfile"
authors = ["Jeremie Gobeil <jeremie.gobeil@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0.1"
pandas = "^2.0.3"
dask = "^2023.8.0"
distributed = "^2023.8.0"
ticstat = "^0.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
numpy = "^1.25.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
