[package]
name = "mitmproxy_rs"
license = "MIT"
authors= [
    "Fabio Valentini <decathorpe@gmail.com>",
    "Maximilian Hils <cargo@maximilianhils.com>",
]
version= "0.2.2"
repository= "https://github.com/mitmproxy/mitmproxy-rs"
edition= "2021"
rust-version= "1.65.0"
publish= false

[lib]
name = "mitmproxy_rs"
crate-type = ["cdylib"]

[dependencies]
mitmproxy = { path = "local_dependencies/mitmproxy" }
anyhow = { version = "1.0.71", features = ["backtrace"] }
data-encoding = "2.4.0"
log = "0.4.18"
once_cell = "1"
pyo3 = { version = "0.18.2", features = ["abi3", "abi3-py310", "extension-module", "anyhow"] }
pyo3-asyncio = { version = "0.18.0", features = ["tokio-runtime"] }
pyo3-log = "0.8.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
tokio = { version = "1.29", features = ["macros", "net", "rt-multi-thread", "sync"] }
x25519-dalek = "2.0.0-pre.1"

# optional dependencies for tracing support
console-subscriber = { version = "0.1.9", optional = true }

[features]
tracing = ["console-subscriber"]
