[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mkdocs-inline-svg-plugin"
description = 'MkDocs plugin for inlining svg-href img tags'
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = ["MkDocs"]
authors = [
  { name = "Oni Boni", email = "oniboni@mailbox.org" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
	"mkdocs <= 1.4.2",
	"requests <= 2.31.0",
	"beautifulsoup4 <= 4.12.0",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/oniboni/mkdocs-inline-svg-plugin#readme"
Issues = "https://github.com/oniboni/mkdocs-inline-svg-plugin/issues"
Source = "https://github.com/oniboni/mkdocs-inline-svg-plugin"

[project.entry-points."mkdocs.plugins"]
inline-svg = "inline_svg.plugin:InlineSvgPlugin"

[tool.hatch.version]
path = "src/inline_svg/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/inline_svg"]

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=inline_svg --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[tool.hatch.envs.docs]
dependencies = [
  "mkdocs-material",
	"mkdocs-kroki-plugin"
]
[tool.hatch.envs.docs.scripts]
build = "mkdocs build --clean --strict"
serve = "mkdocs serve --dev-addr localhost:8000 -vv"

[tool.hatch.envs.dev]
dependencies = [
  "pre-commit",
  "ruff",
  "black",
  "commitizen",
  "pip-audit",
]
post-install-commands = [
  "pre-commit install --hook-type commit-msg --hook-type pre-push"
]
[tool.hatch.envs.dev.scripts]
audit = "pip-audit"
lint = "ruff check src/"
format = "black src/"
commit = "cz commit"


[tool.ruff]
line-length = 99
target-version = "py310"

[tool.black]
line-length = 99
target-version = ['py310']

# TODO: find a way testing mkdocs plugins
# [[tool.hatch.envs.test.matrix]]
# python = ["39", "310", "311"]

# [tool.coverage.run]
# branch = true
# parallel = true

# [tool.coverage.report]
# exclude_lines = [
#   "no cov",
#   "if __name__ == .__main__.:",
#   "if TYPE_CHECKING:",
# ]
