[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[project]
name = "nova-python"
authors = [
    {name = "Leander <@henceiusegentoo>"}
]

description = "ðŸ Python library for accessing the Nova API"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

repository = "https://github.com/NovaOSS/nova-python"

[tool.maturin]
features = ["pyo3/extension-module"]