[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blockchain_todo"
dependencies = ["loongchain","fire"]
version = "1.0"
authors = [
  { name="Crillerium", email="crillerium@outlook.com" },
]
description = "A Blockchain Supported To Do List"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Home-page" = "https://github.com/crillerium/"

[project.scripts]
todo = "blockchain_todo.app:main"